config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stockapp/', include("stockapp.urls")),

]

stockapp/urls.py
from rest_framework.routers import DefaultRouter

from django.urls import path, include
from stockapp.views import KospiData, ChartView, KospiViewSet, KospiCreate, KospiDelete

app_name = "stockapp"

router = DefaultRouter()
router.register(r'post/', KospiViewSet)

urlpatterns = [
    path('api/',include(router.urls)),
    path('chart/', ChartView.as_view(), name="chart"),
    path('data/', KospiData),
    path('create/', KospiCreate, name="create"),
    path('delete/<int:pk>', KospiDelete, name="delete"),
]

stockapp/models.py
from django.db import models


class Kospi(models.Model):
    date = models.DateField(null=False, unique=True)
    close = models.FloatField(null=True)
    open = models.FloatField(null=True)

stockapp/forms.py
from django import forms
from django.forms import ModelForm
from django import forms
from stockapp.models import Kospi


class KospiCreationForm(ModelForm):
    class Meta:
        model = Kospi
        fields = '__all__'
        wigets = {
            'date' : forms.DateInput(attrs={'type': 'date'})
        }

stockapp/views.py
from time import strptime, mktime

from rest_framework.viewsets import ModelViewSet

from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect
from django.views import View
from django.http.response import JsonResponse
from django.views.generic import CreateView, DeleteView
from django.views.generic.edit import FormMixin
from django.contrib import messages


from stockapp.models import Kospi
from stockapp.forms import KospiCreationForm
from stockapp.serializers import KospiSerializer


def KospiData(request):
    stocks = Kospi.objects.all().order_by('date')

    close_list = []
    open_list = []

    for stock in stocks:
        times = strptime(str(stock.date), '%Y-%m-%d')
        utc_now = mktime(times) * 1000

        close_list.append([utc_now, stock.close])
        open_list.append([utc_now, stock.open])

    data = {
        'close': close_list,
        'open': open_list,
    }

    return JsonResponse(data)

    
class KospiViewSet(ModelViewSet):
    queryset = Kospi.objects.all()
    serializer_class = KospiSerializer


class ChartView(View):
    def get(self, request, *args, **kwargs):
        kospi_list = Kospi.objects.order_by('date')
        return render(request, 'stockapp/chart.html', {'kospi_list': kospi_list})
    

def KospiCreate(request):
    if request.method == "POST":
        date = request.POST["date"]
        open = request.POST["open"]
        close = request.POST["close"]
        kospi_list = Kospi.objects.order_by('date')
        
        if not date or not open or not close:
            message = "필드에 누락된 값이 있습니다."
            return render(request, 'stockapp/chart.html', {'kospi_list': kospi_list, 'message': message})
        elif Kospi.objects.filter(date=date):
            message = "날짜가 중복됩니다."
            return render(request, 'stockapp/chart.html', {'kospi_list': kospi_list, 'message': message})
        else:
            Kospi(date=date, open=open, close=close).save()
            message = "추가 완료"
            kospi_list = Kospi.objects.order_by('date')
            return render(request, 'stockapp/chart.html', {'kospi_list': kospi_list, 'message': message})
            
    else:
        kospi_list = Kospi.objects.order_by('date')
        return render(request, 'stockapp/chart.html', {'kospi_list': kospi_list})


def KospiDelete(request, pk):
    if request.method == "POST":
        target_kospi = Kospi.objects.get(pk=pk)
        target_kospi.delete()
        
        kospi_list = Kospi.objects.order_by('date')
        message = "삭제 완료"
        return render(request, 'stockapp/chart.html', {'kospi_list': kospi_list, 'message': message})
        
    else:
        kospi_list = Kospi.objects.order_by('date')
        return render(request, 'stockapp/chart.html', {'kospi_list': kospi_list})
        

stockapp/templates/stockapp/chart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="container">

  <script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{#  <script src="{% static 'js/chart.js' %}"></script>#}

  <script>
  function setChart() {
    Highcharts.setOption({
      global: {
        useUTC: false
      }
    });
  };

  $.ajax({
    url: "/stockapp/data/",
    dataType: 'json',
    success: function (data) {

      Highcharts.setOptions({
        global: {
          useUTC: false
        }
      });

      Highcharts.stockChart("container", {

        chart: {
          height: 500
        },

        title: {
          text: '코스피 지수'
        },

        rangeSelector: {
          selected: 5,
          inputEnabled: false
        },

        xAxis: {
          type: 'datetime',
          labels:{
            formatter: function(){
              return Highcharts.dateFormat('%y.%m.%d', this.value);
            },
            step: 3
          }
        },

        yAxis: {
          labels: {
            format: '{value}',
            style: {
              color: 'rgba(0,0,0,.6)',
            },
            x: 30,
          },
          opposite: false,
          tickInterval: 50,
        },

        tooltip: {
          xDateFormat: '%Y-%m-%d',
          split: true
        },

        series: [{
            name: '시가',
            data: data.open,
            color: 'rgba(0,200,0,.6)',
            lineWidth: 2
        },
        {
            name: '종가',
            data: data.close,
            lineWidth: 3
        }],

        legend: {
          enabled: true,
          align: 'left',
          verticalAlign: 'top',
          floating: true,
          x: 30,
          y: 70
        },

        responsive: {
          rules: [{
            condition: {
              maxWidth: 600
            },
            chartOptions: {
              chart: {
                height: 300
              },
              navigator: {
                enabled: false
              }
            }
          }]
        }
      });
    }
  });
  </script>

</div>
<div>
  {% include 'stockapp/createkospi.html'%}
</div>
<div>
  {% include 'stockapp/kospi_list.html' %}
</div>

{% endblock %}

stockapp/templates/stockapp/createkospi.html
{% block content %}

<div style="text-align: center;">
    <h4>Kospi Create</h4>
    <form action="{% url 'stockapp:create' %}" method="POST">
        {% csrf_token %}
        <label>날짜</label><input type="date" name="date">
        <label>시가</label><input type="number" step="0.01" name="open">
        <label>종가</label><input type="number" step="0.01" name="close">
        
        <input style="color:cornflowerblue; text-decoration:none; cursor: pointer;"\
               type="submit" value="추가">
    </form>
</div>

{% endblock content %}

stockapp/templates/stockapp/home.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>NSC_졸음운전방지</title>
</head>
<style>
  * {
      box-sizing: border-box;
    }

  body {
    margin: 0;
  }

/* Style the header */
.header {
background-color: #56fdbd;
padding: 10px;
text-align: center;
}


/* Style the top navigation bar */
.topnav {
  overflow: hidden;
  background-color: rgb(73, 88, 254);
}

/* Style the topnav links */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 10px 16px;
  text-decoration: none;
}

/* Change color on hover */
.topnav a:hover {
  background-color: #ddd;
  color: rgb(31, 123, 245);
}

/* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 50%;
  padding: 15px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media screen and (max-width:600px) {
  .column {
    width: 100%;
  }
}

</style>
</head>
<body>
  <div class="header">
      <a href="base.html"><h1>No Sleep Car</h1></a>
  </div>
  <div class="topnav">
      <a href="../index.html">Home</a>
      <a href="../setting.html">설정</a>
      <a href="../mypage.html">My Page</a>
      <a href="../login.html">Log In</a>
  </div>

<style> 
  .newspaper {
   column-count: 2;
      }
</style>

  <!-- <div class="row"> -->
    <div class="column" style="background-color: #ffffff" align="center">
      <h3>Driving Monitor</h3>
        <video height="400" width="600" autoplay align="center"></video>
          <script>
              const video = document.querySelector('video');
              navigator.mediaDevices.getUserMedia({ video: { width: 426, height: 240 } }).then((stream) => video.srcObject = stream);
              const FPS = 3;
              ws.onopen = () => {
              setInterval(() => {
              ws.send(getFrame());
                  }, 100 / FPS);
              }
          </script>
    <!-- </div>
    <div align="center"> -->
      <button class="button" type="button" id="testStartBtn" align="center">START</button>
      <button class="button" type="button" id="testStopBtn">STOP</button>
    </div>
    
    <div class="column" style="background-color: #ffffff" align="center">
      <h3>Streaming Data</h3>
        <video height="400" width="600" align="center"></video>
          <script>
              const video = document.querySelector('video');
              navigator.mediaDevices.getUserMedia({ video: { width: 426, height: 240 } }).then((stream) => video.srcObject = stream);
              const FPS = 3;
              ws.onopen = () => {
              setInterval(() => {
              ws.send(getFrame());
                  }, 100 / FPS);
              }
          </script>
    </div>
  </div>
<body>
  <h1>
    ★
  </h1>

  {% block content %}
  {% endblock %}


stockapp/templates/stockapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Main</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">



<style>
    * {
        box-sizing: border-box;
      }

    body {
      margin: 0;
    }

/* Style the header */
.header {
  background-color: #56fdbd;
  padding: 10px;
  text-align: center;
}


/* Style the top navigation bar */
.topnav {
    overflow: hidden;
    background-color: rgb(73, 88, 254);
  }
  
  /* Style the topnav links */
  .topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 10px 16px;
    text-decoration: none;
  }
  
  /* Change color on hover */
  .topnav a:hover {
    background-color: #ddd;
    color: rgb(31, 123, 245);
  }

/* Create two equal columns that floats next to each other */
.column {
    float: left;
    width: 50%;
    padding: 15px;
  }
  
  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
  
  /* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
  @media screen and (max-width:600px) {
    .column {
      width: 100%;
    }
  }

  
</style>
</head>
<body>
    <div class="header">
        <h1>No Sleep Car</h1>
    </div>

    <div class="topnav">
        <a href="index.html">Home</a>
        <a href="setting.html">설정</a>
        <a href="mypage.html">My Page</a>
        <a href="login.html">Log In</a>
    </div>

<style> 
    .newspaper {
     column-count: 2;
        }
</style>

    <!-- <div class="row"> -->
      <div class="column" style="background-color: #ffffff" align="center">
        <h3>Driving Monitor</h3>
          <video height="400" width="600" autoplay align="center"></video>
            <script>
                const video = document.querySelector('video');
                navigator.mediaDevices.getUserMedia({ video: { width: 426, height: 240 } }).then((stream) => video.srcObject = stream);
                const FPS = 3;
                ws.onopen = () => {
                setInterval(() => {
                ws.send(getFrame());
                    }, 100 / FPS);
                }
            </script>
      <!-- </div>
      <div align="center"> -->
        <button class="button" type="button" id="testStartBtn" align="center">START</button>
        <button class="button" type="button" id="testStopBtn">STOP</button>
      </div>
      
      <div class="column" style="background-color: #ffffff" align="center">
        <h3>Streaming Data</h3>
          <video height="400" width="600" align="center"></video>
            <script>
                const video = document.querySelector('video');
                navigator.mediaDevices.getUserMedia({ video: { width: 426, height: 240 } }).then((stream) => video.srcObject = stream);
                const FPS = 3;
                ws.onopen = () => {
                setInterval(() => {
                ws.send(getFrame());
                    }, 100 / FPS);
                }
            </script>
      </div>
    </div>

    

</body>
</html>

​

stockapp/templates/stockapp/kospi_list.html
{% block content %}

<div style="text-align: center;">
    <h4>Kospi List</h4>
    
    {% if kospi_list %}
        
        {% for kospi in kospi_list %}
        <span>{{ kospi.date }}</span>
            <form action="{% url 'stockapp:delete' kospi.pk %}" method="POST">
                {% csrf_token %}
                <input style="color: red; cursor: pointer" type="submit" value='X'>
            </form>
            <br>
        {% endfor %}
            
    {% endif %}
    
    <p style="color: blue;">
        {% if message %}
            {{ message }}
        {% endif %}
    </p>
</div>

<script>
    function deletekospi(pk){
        console.log("del")
        console.log(pk)
        $.ajax({
            type: "POST",
            url: "/stockapp/delete/"+pk,
            data: {
                'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
            },
        });
    }
</script>
{% endblock content %}

stockapp/templates/stockapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="style.css">
<script src="http://code.jquery.com/jquery-3.4.1.min.js"></script>
<script>
var emp = { 
		"id" : "abcd",
		"pw" : "1234",
		"name" : "홍길동",
		"point" : "1250"
};
$(document).ready(function(){
	$("#loginb").click(function(){
	     var sid = $("#uid").val();
	     var spw = $("#pwd").val();
	     
	     if(sid=="" || spw=="")
	     {
			$("#result").text("아이디와 비밀번호를 입력해 주세요").css("color","black");			    	 
	     }else{
			if(emp.id==sid && emp.pw==spw){
				alert(emp.name+"님 로그인 하셨습니다.\n현재 보유하신 포인터는 "+emp.point+"점 입니다");
				$("#loginok").submit();
			}else{
				alert("아이디 또는 비밀번호가 틀립니다.");
				$("#uid").val("");
				$("#pwd").val("");
				$("#uid").focus();
			} 
	     }		
	});	
	
	$("#searId").click(function(){
		$("#back").css("display", "block");
	    $("#popup").css("display", "block");
	});
	
	$(".close").click(function(){
		$("#back").css("display", "none");
	    $("#popup").css("display", "none");
	});
});
</script>
<style>
    * {
        box-sizing: border-box;
      }

    body {
      margin: 0;
    }

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: center;
}


/* Style the top navigation bar */
.topnav {
    overflow: hidden;
    background-color: rgb(73, 88, 254);
  }
  
  /* Style the topnav links */
  .topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 10px 16px;
    text-decoration: none;
  }
  
  /* Change color on hover */
  .topnav a:hover {
    background-color: #ddd;
    color: rgb(31, 123, 245);
  }
  
</style>
</head>
<body>
    <div class="header">
        <h1>No Sleep Car</h1>
    </div>

    <div class="topnav">
        <a href="index.html">Home</a>
        <a href="setting.html">설정</a>
        <a href="mypage.html">My Page</a>
        <a href="login.html">Log In</a>
    </div>


<section id="section2">
  <div class="container">
    <div class="loginBox">
      
        <div class="box">
          <div class="social logo">
              <h1>소셜 로그인하기</h1>
                <button class="facebook">Google ID로 로그인</button>
                <button class="twitter">카카오 ID로 로그인</button>
                <button class="naver">네이버 ID로 로그인</button>
          </div>
        </div>             
    </div>
  </div>    
</section>



    

</body>
</html>

​

stockapp/templates/stockapp/mypage.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>My Page</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">



<style>
    * {
        box-sizing: border-box;
      }

    body {
      margin: 0;
    }

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 10px;
  text-align: center;
}


/* Style the top navigation bar */
.topnav {
    overflow: hidden;
    background-color: rgb(73, 88, 254);
  }
  
  /* Style the topnav links */
  .topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 10px 16px;
    text-decoration: none;
  }
  
  /* Change color on hover */
  .topnav a:hover {
    background-color: #ddd;
    color: rgb(31, 123, 245);
  }

/* Create two equal columns that floats next to each other */
.column {
    float: left;
    width: 50%;
    padding: 15px;
  }
  
  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
  
  /* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
  @media screen and (max-width:600px) {
    .column {
      width: 100%;
    }
  }

  
</style>
</head>
<body>
    <div class="header">
        <h1>No Sleep Car</h1>
    </div>

    <div class="topnav">
        <a href="index.html">Home</a>
        <a href="setting.html">설정</a>
        <a href="mypage.html">My Page</a>
        <a href="login.html">Log In</a>
    </div>

    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 80%;
        height: 100px;
        margin-top: 30px;
        margin-left: 50px;
        margin-right: 50px;

      }
      
      td, th {
        border: 1px solid #e1dfdf;
        text-align: left;
        padding: 8px;
      }
      
      tr:nth-child(even) {
        background-color: hsl(0, 0%, 100%);
      }
      </style>
      </head>
      <body>
      
      <h2>My Info</h2>
      
      <table>
        <tr>
          <th>닉네임</th>
          <th>이름</th>
          
        </tr>
        <tr>
          <td>pororo</td>
          <td>abc</td>
          
        </tr>
        
      </table>
      
      <h2>분석 자료</h2>
      
      <table>
        <tr>
          <th>졸음 횟수</th>
          <th>기타 통계</th>
          
        </tr>
        <tr>
          <td>Graph</td>
          <td>Graph</td>
          
        </tr>
        
      </table>

    

</body>
</html>

​

stockapp/templates/stockapp/setting.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Setting</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="css/style.css">


<style>
    * {
        box-sizing: border-box;
      }

    body {
      margin: 0;
    }

/* Style the header */
.header {
  background-color: #fafad4;
  padding: 10px;
  text-align: center;
}


/* Style the top navigation bar */
.topnav {
    overflow: hidden;
    background-color: rgb(73, 88, 254);
  }
  
  /* Style the topnav links */
  .topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 10px 16px;
    text-decoration: none;
  }
  
  /* Change color on hover */
  .topnav a:hover {
    background-color: #ddd;
    color: rgb(31, 123, 245);
  }

/* Create two equal columns that floats next to each other */
.column {
    float: left;
    width: 50%;
    padding: 15px;
  }
  
  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
  
  /* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
  @media screen and (max-width:600px) {
    .column {
      width: 100%;
    }
  }

  
</style>
</head>
<body>
    <div class="header">
        <h1>No Sleep Car</h1>
    </div>

    <div class="topnav" align="left">
        <a href="index.html">Home</a>
        <a href="setting.html">설정</a>
        <a href="mypage.html">My Page</a>
        <a href="login.html">Log In</a>
    </div>


<br>
  <h2>알림음 선택</h2>

    <p><ol></p>
      <li><a a href=>소리 1</a></li><br>
      <li><a a href=>소리 2</a></li><br>
      <li><a a href=>소리 3</a></li><br>
    </ol>  

    

</body>
</html>

​

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>STOCK Chart</title>
</head>
<body>
  <h1>
    Kospi data
  </h1>

  {% block content %}
  {% endblock %}

</body>
</html>